# Arrays

In [1]:
import numpy as np
l = [1,2,3,4,5,7,7]
x = np.array(l)
print("Array = ",x)
print("Dimensions",x.ndim)

Array =  [1 2 3 4 5 7 7]
Dimensions 1


In [2]:
z = np.array([[2,3,4,5],[2,3,5,6]])
print(z)
print(z.ndim)

[[2 3 4 5]
 [2 3 5 6]]
2


In [3]:
y = np.array([[2,5,4],[2,4,5],[3,4,5]],ndmin = 32)
print(y)
print(y.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[2 5 4]
                               [2 4 5]
                               [3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
32


# Zeros

In [4]:
ar_zeros = np.zeros(2)
arr_zeros = np.zeros((4,5))

print(ar_zeros)
print()
print(arr_zeros)

[0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Ones

In [5]:
ar_ones = np.ones(7)
arr_ones = np.ones((4,7))

print(ar_ones)
print()
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# Range


In [6]:
ar_range = np.arange(0,6)
print(ar_range)

[0 1 2 3 4 5]



# Empty

In [7]:
arr_empty = np.empty(3)
print(arr_empty)

[0. 0. 0.]


# Digonal

In [8]:
ar_dia = np.eye(2,8)
print(ar_dia)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]


# LinSpace

In [9]:
arr_lin = np.linspace(1,2,num=20)
print(arr_lin)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


# Functions

In [10]:
#1 rand() :This function is used to generate a random value between 0 to 1
#2 randn():This function is used to generate a randomn value close to zero. 
#This may Retrurn positive or negative numbers as well
#3 ranf(): The function for doing random sampling in numpy.it returns an array
#of specified shape and fills it with random floats in the half open interval [0.0,1.0)
#4 randint(): The function is used to generate a random numbers

# Random

# rand()

In [11]:
var = np.random.rand(4,6)

print(var)

[[0.8814815  0.76623291 0.9763696  0.46449128 0.26161084 0.83288742]
 [0.974801   0.24092543 0.56859573 0.32980726 0.67892151 0.5658052 ]
 [0.31416759 0.0178945  0.36052628 0.62559348 0.01908482 0.13934527]
 [0.75997489 0.63197865 0.65084508 0.10530604 0.19588362 0.00906507]]


# randn()

In [120]:
var1 = np.random.randn(3,6)
print(var1)

[[ 0.03532418  0.23616779  0.85715722 -0.72314818  0.28262543 -0.25937687]
 [-1.54877904  0.87846198  0.77464205  0.40932184 -0.55247737  1.6140525 ]
 [-0.70311824  1.61300423 -0.6512629  -1.82734054  0.63580365 -0.57815637]]


# ranf()

In [13]:
var2 = np.random.ranf(3)

print(var2)


[0.91551996 0.87518018 0.35724317]


# randint()

In [14]:
var3 = np.random.randint(2,78,999)

print(var3)

[72 61 65 53 43 42 11 52 29 31 43 12 28 54 23 76 33  2 62 54 13 42 57 55
 45 76  5 35 28 30 52 30  5  4 57 57 35 40 29 62 40 50 70 32 76 34 38 17
  5  5 25 28 45 59 33 56 10 58 19 25 76  3 63 43 40  3 58 25 15 14 40 28
 33 33 19 72 72 20 69 18 69 52  3 47 48 29 16 67 16 66  4 26 20  7 63 33
 41 15 49 44 53 24 77  4 30 73 58 56 40 68 48 49 14 73  6 15  9 69 24 66
 25  5 70 57 45 29 59  4 41 19 32 66 40 56 30 39 46  7 36 44 17 24 63 45
 31 59  5 49 19  4 73 69 11 28 15 39 10 73 37 14 21 39 31 50 59  9 77 29
 63  9 34 77 28  6 46  7  9 20 60 16 58 49 54 27 21 14  9 55 30 11 12  5
 73 43 39 34 47 64 18 24 70 12 62 54 31 42 41 23 73 51 11 10  6 35 10 61
 41 48 45 74 26 19 37 58 50 28 31  4 68 46 46 50 23 47 49 40 56 38 25 13
 28 27  2 50 62 65 53 39 49 13 72 15 15 19  9  5 54 41 50 55 26 20 70  7
 57 54  9 74 60 14  4 17 43 15 26 76 47 47 48 70  4 61 33 64 67 38 50 45
 44 25 51 52 67 63 14 34 18 70  4  6 59 19 46 19 67 22 44 44 68 18 50 56
 57 14 14 74 69 55 14 73 37 15 18 32 40 13 30 61 30

In [15]:
x = np.zeros(3)
z = np.zeros((4,6))
print(x)

print(z)

[0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
a = np.ones(6)
print(a,"\n")
b = np.ones((5,7))
print(b)

[1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
c = np.empty(6)

print(c)

[1. 1. 1. 1. 1. 1.]


In [18]:
d = np.eye(5)
e = np.eye(6,7)

print(d)

print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [19]:
f = np.arange(3,7,2)
print(f)

[3 5]


In [20]:
g = np.random.rand(6,6)

print(g)

[[0.81127909 0.49858931 0.26683081 0.58271395 0.87535003 0.57313424]
 [0.79717311 0.57328288 0.23384172 0.11971984 0.49918791 0.65088854]
 [0.89519774 0.32720076 0.3311332  0.23247596 0.34153602 0.52604098]
 [0.57103235 0.23473297 0.67476614 0.49917267 0.3959806  0.84758711]
 [0.37130875 0.18318527 0.16589017 0.81798366 0.04585094 0.30462362]
 [0.50709811 0.60477194 0.04172544 0.17820184 0.72668889 0.87059831]]


In [21]:
h = np.random.randn(4,7)

print(h)

[[-0.71426852 -2.31693617  2.35586664  0.26644258 -0.97760453 -0.20312814
   1.08768743]
 [-1.53818626 -1.36566334  0.74685187  0.34622814  1.01213826 -1.43030114
  -0.53360646]
 [-0.73428014 -1.07891272  0.02122594 -0.23942977 -1.85899421  0.47672598
   2.57127714]
 [-1.13016612  0.96562061 -0.76989674  1.17791578 -1.96437812 -0.64239115
   0.907118  ]]


In [22]:
i = np.random.ranf(3)

print(i)

[0.3680692  0.67549887 0.88765226]


In [23]:
j = np.random.randint(2,7,6)

print(j)

[5 5 2 6 3 6]


# Arrays

In [24]:
x = np.array([2,3,4,5,6,7],dtype = 'f')
print(x)
print(x.dtype)

[2. 3. 4. 5. 6. 7.]
float32


In [25]:
x1 = np.array([2,3,4,5,6,7])
print(np.complex64(x1))

[2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


# Arithematic Operations

In [26]:
x2 = np.array([2,3,4,5,6,7])


In [27]:
x3  = x2+3
print(x3)

[ 5  6  7  8  9 10]


In [28]:
x4 = x3+x2
print(x4)

[ 7  9 11 13 15 17]


In [29]:
var1 = np.array([2,3,4,5,6,7])

var2 = var1**3

print(var2)

[  8  27  64 125 216 343]


In [30]:
var4 = var1*2

In [31]:
var4

array([ 4,  6,  8, 10, 12, 14])

In [32]:
var4 = 1/var1

print(var4)

[0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]


In [33]:
a = np.array([[2,3,4,5],[4,3,6,7]])
b = np.array([[2,4,3,5],[5,4,3,8]])

c = np.add(a,b)
print(c)
print(c.shape)

[[ 4  7  7 10]
 [ 9  7  9 15]]
(2, 4)


In [34]:
d = a*b
print(d)

[[ 4 12 12 25]
 [20 12 18 56]]


In [35]:
e = np.reciprocal(d)

print(e)

[[0 0 0 0]
 [0 0 0 0]]


# Arithematic Function

In [36]:
#1D Array
arr = np.array([2,4,1,5,7,63,57,35])

print("Maximum Element in an Array  = ",arr.max(),"At index ",arr.argmax())

print("Minimum Element in an Array  = ",arr.min(),"At index",arr.argmin())

print("Square_Root Element of an Array  = ",np.sqrt(arr))
print(np.cumsum(arr))
print(np.sin(arr))
print(np.cos(arr))

Maximum Element in an Array  =  63 At index  5
Minimum Element in an Array  =  1 At index 2
Square_Root Element of an Array  =  [1.41421356 2.         1.         2.23606798 2.64575131 7.93725393
 7.54983444 5.91607978]
[  2   6   7  12  19  82 139 174]
[ 0.90929743 -0.7568025   0.84147098 -0.95892427  0.6569866   0.1673557
  0.43616476 -0.42818267]
[-0.41614684 -0.65364362  0.54030231  0.28366219  0.75390225  0.98589658
  0.89986683 -0.90369221]


In [37]:
#2D Array
ar = np.array([[2,3,4,5,6,],[3,4,5,6,7],[4,5,6,7,7]])
print(ar)
print("Minimum element in every column = ",np.min(ar,axis = 0))#if axis is 0 it will check column wise
print("Maximum element in every row = ",np.max(ar,axis = 1))#if axis is 1 it will check Row wise

print(np.cumsum(ar))
print("")
print(np.sin(ar))
print("")
print(np.cos(ar))
print("Square_Root Element of an Array  = ",np.sqrt(ar))

[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 7]]
Minimum element in every column =  [2 3 4 5 6]
Maximum element in every row =  [6 7 7]
[ 2  5  9 14 20 23 27 32 38 45 49 54 60 67 74]

[[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866   0.6569866 ]]

[[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
 [-0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.65364362  0.28366219  0.96017029  0.75390225  0.75390225]]
Square_Root Element of an Array  =  [[1.41421356 1.73205081 2.         2.23606798 2.44948974]
 [1.73205081 2.         2.23606798 2.44948974 2.64575131]
 [2.         2.23606798 2.44948974 2.64575131 2.64575131]]


# Shape and Reshape

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.shape)
arr1 = arr.reshape(3,2,2)
print(arr1.ndim)
print(arr1)

(12,)
3
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [39]:
z = np.array([2,3,4,5,6,7,7,4])

print(z.ndim)

y = z.reshape(4,2)
print(y)

1
[[2 3]
 [4 5]
 [6 7]
 [7 4]]


In [40]:
x1  =  np.array([2,3,4])
x2 = np.array([[2],[3],[5]])
print(x1+x2)

[[4 5 6]
 [5 6 7]
 [7 8 9]]


In [41]:
x3 = np.array([2,6,7,8])
x4 = np.array([[2,3,4,4],[4,5,5,4],[3,5,6,4]])

print(x3+x4)

[[ 4  9 11 12]
 [ 6 11 12 12]
 [ 5 11 13 12]]


# Indexing

In [42]:
#1D
z = np.array([2,3,4,5,6])
              #0,1,2,3,4 positive indexing
            #-5,-4,-3,-2,-1 negative indexing
print(z)

print(z[3])
print(z[-2])

[2 3 4 5 6]
5
5


In [43]:
#2D
za = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.ndim(za))
print(za)
print(za[2,0])
print(za[0:4,1:4])

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
7
[[2 3]
 [5 6]
 [8 9]]


In [44]:
#3D
zam = np.array([[[[2,3,5],[10,6,8]],[[7,9,1],[2,3,4]],[[11,12,13],[2,3,4]]]])
print(zam)
print(zam[0,2,0,2])

[[[[ 2  3  5]
   [10  6  8]]

  [[ 7  9  1]
   [ 2  3  4]]

  [[11 12 13]
   [ 2  3  4]]]]
13


In [45]:
teh = np.array([[2,3,4,5,6,7],[10,98,6,44,34,345],[43,54,54,33,64,54]])

print(teh)
print(teh[1,3])

print()
print(teh[1:,1::2])

[[  2   3   4   5   6   7]
 [ 10  98   6  44  34 345]
 [ 43  54  54  33  64  54]]
44

[[ 98  44 345]
 [ 54  33  54]]


# Iteration Numpy Arrays

In [46]:
var = np.array([1,2,3,4,5,6,7,8,9,0])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5 6 7 8 9 0]

1
2
3
4
5
6
7
8
9
0


In [47]:
var = np.array([1,2,3,4,5,6,7,8,9,0])
print(var)
print()
for i in np.nditer(var):#nditer iterate as dimensions
    print(i)

[1 2 3 4 5 6 7 8 9 0]

1
2
3
4
5
6
7
8
9
0


In [48]:
var = np.array([1,2,3,4,5,6,7,8,9,0])
print(var)
print()
for i in np.ndenumerate(var):#ndenemurate iterate with index
    print(i)

[1 2 3 4 5 6 7 8 9 0]

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)
((4,), 5)
((5,), 6)
((6,), 7)
((7,), 8)
((8,), 9)
((9,), 0)


In [49]:
var1 = np.array([[2,3,4,5,6,7],[2,3,4,22,4,22],[54,223,45,75,75,54]])
print(var1)
print()
for i in var1:
    for j in i:
       print(j)

[[  2   3   4   5   6   7]
 [  2   3   4  22   4  22]
 [ 54 223  45  75  75  54]]

2
3
4
5
6
7
2
3
4
22
4
22
54
223
45
75
75
54


In [50]:
var1 = np.array([[2,3,4,5,6,7],[2,3,4,22,4,22],[54,223,45,75,75,54]])
print(var1)
print()
for i in np.nditer(var1):
    print(i)


[[  2   3   4   5   6   7]
 [  2   3   4  22   4  22]
 [ 54 223  45  75  75  54]]

2
3
4
5
6
7
2
3
4
22
4
22
54
223
45
75
75
54


In [51]:
var1 = np.array([[2,3,4,5,6,7],[2,3,4,22,4,22],[54,223,45,75,75,54]])
print(var1)
print()
   
for j in np.ndenumerate(var1):
    print(j)

[[  2   3   4   5   6   7]
 [  2   3   4  22   4  22]
 [ 54 223  45  75  75  54]]

((0, 0), 2)
((0, 1), 3)
((0, 2), 4)
((0, 3), 5)
((0, 4), 6)
((0, 5), 7)
((1, 0), 2)
((1, 1), 3)
((1, 2), 4)
((1, 3), 22)
((1, 4), 4)
((1, 5), 22)
((2, 0), 54)
((2, 1), 223)
((2, 2), 45)
((2, 3), 75)
((2, 4), 75)
((2, 5), 54)


In [52]:
var2 = np.array([[[2,3,4,5,6,7]],[[2,3,4,5,6,7]]])
print(var2)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[2 3 4 5 6 7]]

 [[2 3 4 5 6 7]]]

2
3
4
5
6
7
2
3
4
5
6
7


In [53]:
var2 = np.array([[[2,3,4,5,6,7]],[[2,3,4,5,6,7]]])
print(var2)
print()
for i ,d in np.ndenumerate(var2):
    print(i," = ", d)

[[[2 3 4 5 6 7]]

 [[2 3 4 5 6 7]]]

(0, 0, 0)  =  2
(0, 0, 1)  =  3
(0, 0, 2)  =  4
(0, 0, 3)  =  5
(0, 0, 4)  =  6
(0, 0, 5)  =  7
(1, 0, 0)  =  2
(1, 0, 1)  =  3
(1, 0, 2)  =  4
(1, 0, 3)  =  5
(1, 0, 4)  =  6
(1, 0, 5)  =  7


# Copy VS View

In [54]:
#1  Copy:The copy owns the data
#The copy of an array is a new array
#The changes made in the copy data does not reflects in the original data

#2   View: The View Does not owns the data
#A view of the original array
#Any changes made to the view will affet the original array,and any changes
#made to the original may will affect the view

In [55]:
var = np.array([1,2,3,4,5])
var2 = var.copy()
var[1]=90
print("Original: ",var)
print("Copy: ",var2)

Original:  [ 1 90  3  4  5]
Copy:  [1 2 3 4 5]


In [56]:
var3 = np.array([1,2,3,4,5])
var4 = var3.view()
var3[4]=100
print("Original: ",var3)
print("View: ",var4)


Original:  [  1   2   3   4 100]
View:  [  1   2   3   4 100]


# Join Arrays

In [57]:
a_1  = np.array([2,3,4,5,6])
a_2 = np.array([1,9,8,7,6])
new = np.concatenate((a_1,a_2))
print(new)

[2 3 4 5 6 1 9 8 7 6]


In [58]:
ar_1  = np.array([[2,3],[4,5]])
ar_2 = np.array([[1,9],[7,6]])
new_1 = np.concatenate((ar_1,ar_2),axis = 1)
new_1 = np.concatenate((ar_1,ar_2),axis = 0)

print(new_1)

[[2 3]
 [4 5]
 [1 9]
 [7 6]]


In [59]:
ar_1  = np.array([2,3,4,5])
ar_2 = np.array([1,9,7,6])
new_1 = np.stack((ar_1,ar_2),axis = 0)
new_2 = np.hstack((ar_1,ar_2))
new_3 = np.vstack((ar_1,ar_2))
new_4 = np.dstack((ar_1,ar_2))
print(new_1)
print()
print(new_2)
print()
print(new_3)
print()
print(new_4)

[[2 3 4 5]
 [1 9 7 6]]

[2 3 4 5 1 9 7 6]

[[2 3 4 5]
 [1 9 7 6]]

[[[2 1]
  [3 9]
  [4 7]
  [5 6]]]


# Split

In [76]:
var_1 = np.array([2,3,4,5,6,7,8,9,8])
var_2 = np.array_split(var_1,3)
print(var_2)

[array([2, 3, 4]), array([5, 6, 7]), array([8, 9, 8])]


In [78]:
var_3 = np.array([[2,3],[5,6],[8,9]])
var_4 = np.array_split(var_3,3)
print(var_4)

[array([[2, 3]]), array([[5, 6]]), array([[8, 9]])]


# Search Array

In [82]:
#Search sorted array: Which performs a binary search in the array,
#and returns the index where the specifiednvalue would be inserted
#to maintain the search order
zam = np.array([2,3,4,52,6,7,5,2,44,33,2,4,3,2])
eer = np.where(zam==2)

print(eer)

(array([ 0,  7, 10, 13], dtype=int64),)


In [88]:
eerz = np.array([2,3,4,5,7,8])
zame = np.searchsorted(eerz,6,side = "right")
print(zame)

4


In [89]:
eerz = np.array([2,3,4,5,7,8])
zame = np.searchsorted(eerz,[6,7,8,9,8,],side = "right")
print(zame)

[4 5 6 6 6]


In [92]:
#Sorted Array:Ordered sequence is any sequence that has an order corresponding to elements,
#like numeric or alphabetical,asending or decending.
a = np.array([2,5,3,7,434,33,342,234])
print(np.sort(a))
x = np.array(['w','r','a','b','d','c'])
print(np.sort(x))

[  2   3   5   7  33 234 342 434]
['a' 'b' 'c' 'd' 'r' 'w']


In [93]:
#Filter Array: Getting some elements out of an existing array
#and creating a new array out of them
y = np.array(['w','r','a','b','d','c'])
z = [True,False,True,True,False,True]
new = y[z]
print(new)

['w' 'a' 'b' 'c']


In [94]:
#Shuffle
#unique 
#Resize
#Flatten
#Ravel

In [102]:
var2  = np.array([2,4,3,5,4,632,43])
np.random.shuffle(var2)
print(var2)

[  3   5  43   4   4   2 632]


In [111]:
var2  = np.array([2,4,4,3,5,4,632,43])
var23 = np.unique(var2,return_index= True,return_counts= True)
print(var23)

(array([  2,   3,   4,   5,  43, 632]), array([0, 3, 1, 4, 7, 6], dtype=int64), array([1, 1, 3, 1, 1, 1], dtype=int64))


In [126]:
var21  = np.array([[2,4,4,3],[5,4,632,43]])
var3 = np.resize(var21,(2,4))
print(var21,"\n")
print(var3)
print(var3.flatten(order = "K"))
print(np.ravel(var21,order = "C"))

[[  2   4   4   3]
 [  5   4 632  43]] 

[[  2   4   4   3]
 [  5   4 632  43]]
[  4 632]
[  2   4   4   3   5   4 632  43]
[  2   4   4   3   5   4 632  43]


# Insert

In [129]:
zam = np.array([2,3,4,5,6,7])
np.insert(zam,2,8)

array([2, 3, 8, 4, 5, 6, 7])

In [141]:
za_ = np.array([[2,3,4],[5,6,7]])
er_ = np.insert(za_,2,[9,8],axis = 1)
print(er_)

[[2 3 9 4]
 [5 6 8 7]]


In [148]:
he = np.array([2,3,4,5,6])
el = np.append(he,5.8)
print(el)

[2.  3.  4.  5.  6.  5.8]


In [151]:
za_m = np.array([[2,3,4],[5,6,7]])
me = np.append(za_m,[[2,3,4]],axis = 0)
print(me)

[[2 3 4]
 [5 6 7]
 [2 3 4]]


# Matrix

In [158]:
a = np.matrix([2,3,4,5])
b = np.matrix([5,6,7,8])
print(a+b)
print(a-b)
# print(a*b)
print(a)
print(type(a))

[[ 7  9 11 13]]
[[-3 -3 -3 -3]]
[[2 3 4 5]]
<class 'numpy.matrix'>


In [162]:
z = np.matrix([[2,3,4],[5,6,7],[5,6,7]])
d = np.matrix([[2,3,4],[5,6,7],[5,6,7]])
print(z.dot(d))
print()
print(z*d)

[[ 39  48  57]
 [ 75  93 111]
 [ 75  93 111]]

[[ 39  48  57]
 [ 75  93 111]
 [ 75  93 111]]


# Functions

In [164]:
#Transpose
#Swapaxes
#Inverse
#Power
#Determinate
var19 = np.matrix([[2,3],[4,5]])
print(var19)
print()
print(np.transpose(var19))


[[2 3]
 [4 5]]

[[2 4]
 [3 5]]


In [166]:
var20 = np.matrix([[2,3],[4,5]])
print(np.swapaxes(var20,0,1))#matrix , and 0,1 is convert  0 axis to 1 axis

[[2 4]
 [3 5]]


In [167]:
var21 = np.matrix([[2,3],[4,5]])
print(np.linalg.inv(var21))

[[-2.5  1.5]
 [ 2.  -1. ]]


In [171]:
var21 = np.matrix([[2,3],[4,5]])
print(np.linalg.matrix_power(var21,3))

[[116 153]
 [204 269]]


In [172]:
var22 = np.matrix([[2,3],[4,5]])
print(np.linalg.det(var22))

-2.0
